### ISSUE TITLE
Panic when I put an element in and try to generate the root hash

### ISSUE THREAD

**Issue by golangdaddy** [xsleonard/go-merkle#7]
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/xsleonard/go-merkle.(*Tree).generateNodeLevel(0xc420057c10, 0xc4203fa390, 0x1, 0x1, 0xc4203fa390, 0x0, 0x0, 0x14678e0, 0xc4203be380, 0x0, ...)
	/Users/alex/Downloads/go_appengine/gopath/src/github.com/xsleonard/go-merkle/merkle.go:178 +0x306
github.com/xsleonard/go-merkle.(*Tree).Generate(0xc420057c10, 0xc42014a7a0, 0x1, 0x1, 0x14678e0, 0xc4203be380, 0x0, 0x1)
	/Users/alex/Downloads/go_appengine/gopath/src/github.com/xsleonard/go-merkle/merkle.go:137 +0x4d6
github.com/golangdaddy/simple-ledger/models.(*MainBlock).merkleRoot(0xc420057d78, 0x0, 0x0)
	/Users/alex/Downloads/go_appengine/gopath/src/github.com/golangdaddy/simple-ledger/models/model_block.go:69 +0x33c
github.com/golangdaddy/simple-ledger/models.(*MainBlock).AddTX(0xc420057d78, 0xc420070100)
	/Users/alex/Downloads/go_appengine/gopath/src/github.com/golangdaddy/simple-ledger/models/model_block.go:48 +0x101
github.com/golangdaddy/simple-ledger/models.(*MainBlock).AddCoinbase(0xc420057d78, 0xc42008c7b0)
	/Users/alex/Downloads/go_appengine/gopath/src/github.com/golangdaddy/simple-ledger/models/model_block.go:19 +0x17c
main.(*App).initChain(0xc42008d440)
	/Users/alex/Downloads/go_appengine/gopath/src/github.com/golangdaddy/simple-ledger/init_chain.go:13 +0xa3
main.main()
	/Users/alex/Downloads/go_appengine/gopath/src/github.com/golangdaddy/simple-ledger/main.go:49 +0x4a0

**Comment by xsleonard** [comment]
Does #8 fix it?
